import os

background_image_path   = os.getcwd() + '/images/backgrounds/background.jpg'
background_sound_path   = os.getcwd() + '/audio/background.mp3' 
game_logo_path          = os.getcwd() + '/images/donuts_logo.png'
cursor_image_path       = os.getcwd() + '/images/game/hand.png'
sound_on_image_path     = os.getcwd() + '/images/btn-sfx-on.png'
sound_off_image_path    = os.getcwd() + '/images/btn-sfx-off.png'
big_donut_shadow_path   = os.getcwd() + '/images/big-shadow.png'
big_donut_path          = os.getcwd() + '/images/donut.png'
play_image_path         = os.getcwd() + '/images/btn-play.png'
how_to_play_image_path  = os.getcwd() + '/images/btn-howToPlay.png'
return_image_path       = os.getcwd() + '/images/btn-return.png'
red_donut_image_path    = os.getcwd() + '/images/game/gem-01.png'
blue_donut_image_path   = os.getcwd() + '/images/game/gem-02.png'
green_donut_image_path  = os.getcwd() + '/images/game/gem-03.png'
sblue_donut_image_path  = os.getcwd() + '/images/game/gem-04.png'
yellow_donut_image_path = os.getcwd() + '/images/game/gem-05.png'
pink_donut_image_path   = os.getcwd() + '/images/game/gem-06.png'
